export const countries = [
  {
    label: 'North America',
    options: [
      { value: 'us', label: 'United States' },
      { value: 'ca', label: 'Canada' },
      { value: 'mx', label: 'Mexico' },
      { value: 'gt', label: 'Guatemala' },
      { value: 'bz', label: 'Belize' },
      { value: 'sv', label: 'El Salvador' },
      { value: 'hn', label: 'Honduras' },
      { value: 'ni', label: 'Nicaragua' },
      { value: 'cr', label: 'Costa Rica' },
      { value: 'pa', label: 'Panama' },
    ],
  },
  {
    label: 'Caribbean',
    options: [
      { value: 'ag', label: 'Antigua and Barbuda' },
      { value: 'bs', label: 'Bahamas' },
      { value: 'bb', label: 'Barbados' },
      { value: 'cu', label: 'Cuba' },
      { value: 'dm', label: 'Dominica' },
      { value: 'do', label: 'Dominican Republic' },
      { value: 'gd', label: 'Grenada' },
      { value: 'ht', label: 'Haiti' },
      { value: 'jm', label: 'Jamaica' },
      { value: 'kn', label: 'Saint Kitts and Nevis' },
      { value: 'lc', label: 'Saint Lucia' },
      { value: 'vc', label: 'Saint Vincent and the Grenadines' },
      { value: 'tt', label: 'Trinidad and Tobago' },
    ],
  },
  {
    label: 'South America',
    options: [
      { value: 'ar', label: 'Argentina' },
      { value: 'bo', label: 'Bolivia' },
      { value: 'br', label: 'Brazil' },
      { value: 'cl', label: 'Chile' },
      { value: 'co', label: 'Colombia' },
      { value: 'ec', label: 'Ecuador' },
      { value: 'gy', label: 'Guyana' },
      { value: 'py', label: 'Paraguay' },
      { value: 'pe', label: 'Peru' },
      { value: 'sr', label: 'Suriname' },
      { value: 'uy', label: 'Uruguay' },
      { value: 've', label: 'Venezuela' },
    ],
  },
  {
    label: 'Europe',
    options: [
      { value: 'al', label: 'Albania' },
      { value: 'ad', label: 'Andorra' },
      { value: 'am', label: 'Armenia' },
      { value: 'at', label: 'Austria' },
      { value: 'az', label: 'Azerbaijan' },
      { value: 'by', label: 'Belarus' },
      { value: 'be', label: 'Belgium' },
      { value: 'ba', label: 'Bosnia and Herzegovina' },
      { value: 'bg', label: 'Bulgaria' },
      { value: 'hr', label: 'Croatia' },
      { value: 'cy', label: 'Cyprus' },
      { value: 'cz', label: 'Czech Republic' },
      { value: 'dk', label: 'Denmark' },
      { value: 'ee', label: 'Estonia' },
      { value: 'fi', label: 'Finland' },
      { value: 'fr', label: 'France' },
      { value: 'ge', label: 'Georgia' },
      { value: 'de', label: 'Germany' },
      { value: 'gr', label: 'Greece' },
      { value: 'hu', label: 'Hungary' },
      { value: 'is', label: 'Iceland' },
      { value: 'ie', label: 'Ireland' },
      { value: 'it', label: 'Italy' },
      { value: 'kz', label: 'Kazakhstan' },
      { value: 'lv', label: 'Latvia' },
      { value: 'li', label: 'Liechtenstein' },
      { value: 'lt', label: 'Lithuania' },
      { value: 'lu', label: 'Luxembourg' },
      { value: 'mt', label: 'Malta' },
      { value: 'md', label: 'Moldova' },
      { value: 'mc', label: 'Monaco' },
      { value: 'me', label: 'Montenegro' },
      { value: 'nl', label: 'Netherlands' },
      { value: 'mk', label: 'North Macedonia' },
      { value: 'no', label: 'Norway' },
      { value: 'pl', label: 'Poland' },
      { value: 'pt', label: 'Portugal' },
      { value: 'ro', label: 'Romania' },
      { value: 'ru', label: 'Russia' },
      { value: 'sm', label: 'San Marino' },
      { value: 'rs', label: 'Serbia' },
      { value: 'sk', label: 'Slovakia' },
      { value: 'si', label: 'Slovenia' },
      { value: 'es', label: 'Spain' },
      { value: 'se', label: 'Sweden' },
      { value: 'ch', label: 'Switzerland' },
      { value: 'tr', label: 'Turkey' },
      { value: 'ua', label: 'Ukraine' },
      { value: 'uk', label: 'United Kingdom' },
      { value: 'va', label: 'Vatican City' },
    ],
  },
  {
    label: 'Asia',
    options: [
      { value: 'af', label: 'Afghanistan' },
      { value: 'az', label: 'Azerbaijan' },
      { value: 'bd', label: 'Bangladesh' },
      { value: 'bn', label: 'Brunei' },
      { value: 'kh', label: 'Cambodia' },
      { value: 'cn', label: 'China' },
      { value: 'ge', label: 'Georgia' },
      { value: 'in', label: 'India' },
      { value: 'id', label: 'Indonesia' },
      { value: 'ir', label: 'Iran' },
      { value: 'iq', label: 'Iraq' },
      { value: 'il', label: 'Israel' },
      { value: 'jp', label: 'Japan' },
      { value: 'jo', label: 'Jordan' },
      { value: 'kz', label: 'Kazakhstan' },
      { value: 'kw', label: 'Kuwait' },
      { value: 'kg', label: 'Kyrgyzstan' },
      { value: 'la', label: 'Laos' },
      { value: 'lb', label: 'Lebanon' },
      { value: 'my', label: 'Malaysia' },
      { value: 'mv', label: 'Maldives' },
      { value: 'mn', label: 'Mongolia' },
      { value: 'mm', label: 'Myanmar' },
      { value: 'np', label: 'Nepal' },
      { value: 'kp', label: 'North Korea' },
      { value: 'om', label: 'Oman' },
      { value: 'pk', label: 'Pakistan' },
      { value: 'ps', label: 'Palestine' },
      { value: 'ph', label: 'Philippines' },
      { value: 'qa', label: 'Qatar' },
      { value: 'kr', label: 'South Korea' },
      { value: 'sg', label: 'Singapore' },
      { value: 'lk', label: 'Sri Lanka' },
      { value: 'sy', label: 'Syria' },
      { value: 'tw', label: 'Taiwan' },
      { value: 'tj', label: 'Tajikistan' },
      { value: 'th', label: 'Thailand' },
      { value: 'tl', label: 'Timor-Leste' },
      { value: 'tm', label: 'Turkmenistan' },
      { value: 'ae', label: 'United Arab Emirates' },
      { value: 'uz', label: 'Uzbekistan' },
      { value: 'vn', label: 'Vietnam' },
      { value: 'ye', label: 'Yemen' },
    ],
  },
  {
    label: 'Africa',
    options: [
      { value: 'dz', label: 'Algeria' },
      { value: 'ao', label: 'Angola' },
      { value: 'bj', label: 'Benin' },
      { value: 'bw', label: 'Botswana' },
      { value: 'bf', label: 'Burkina Faso' },
      { value: 'bi', label: 'Burundi' },
      { value: 'cv', label: 'Cabo Verde' },
      { value: 'cm', label: 'Cameroon' },
      { value: 'cf', label: 'Central African Republic' },
      { value: 'td', label: 'Chad' },
      { value: 'km', label: 'Comoros' },
      { value: 'cd', label: 'Democratic Republic of the Congo' },
      { value: 'cg', label: 'Republic of the Congo' },
      { value: 'ci', label: "Côte d'Ivoire" },
      { value: 'dj', label: 'Djibouti' },
      { value: 'eg', label: 'Egypt' },
      { value: 'gq', label: 'Equatorial Guinea' },
      { value: 'er', label: 'Eritrea' },
      { value: 'sz', label: 'Eswatini' },
      { value: 'et', label: 'Ethiopia' },
      { value: 'ga', label: 'Gabon' },
      { value: 'gm', label: 'Gambia' },
      { value: 'gh', label: 'Ghana' },
      { value: 'gn', label: 'Guinea' },
      { value: 'gw', label: 'Guinea-Bissau' },
      { value: 'ke', label: 'Kenya' },
      { value: 'ls', label: 'Lesotho' },
      { value: 'lr', label: 'Liberia' },
      { value: 'ly', label: 'Libya' },
      { value: 'mg', label: 'Madagascar' },
      { value: 'mw', label: 'Malawi' },
      { value: 'ml', label: 'Mali' },
      { value: 'mr', label: 'Mauritania' },
      { value: 'mu', label: 'Mauritius' },
      { value: 'ma', label: 'Morocco' },
      { value: 'mz', label: 'Mozambique' },
      { value: 'na', label: 'Namibia' },
      { value: 'ne', label: 'Niger' },
      { value: 'ng', label: 'Nigeria' },
      { value: 'rw', label: 'Rwanda' },
      { value: 'st', label: 'São Tomé and Príncipe' },
      { value: 'sn', label: 'Senegal' },
      { value: 'sc', label: 'Seychelles' },
      { value: 'sl', label: 'Sierra Leone' },
      { value: 'so', label: 'Somalia' },
      { value: 'za', label: 'South Africa' },
      { value: 'ss', label: 'South Sudan' },
      { value: 'sd', label: 'Sudan' },
      { value: 'tz', label: 'Tanzania' },
      { value: 'tg', label: 'Togo' },
      { value: 'tn', label: 'Tunisia' },
      { value: 'ug', label: 'Uganda' },
      { value: 'zm', label: 'Zambia' },
      { value: 'zw', label: 'Zimbabwe' },
    ],
  },
  {
    label: 'Oceania',
    options: [
      { value: 'au', label: 'Australia' },
      { value: 'fj', label: 'Fiji' },
      { value: 'ki', label: 'Kiribati' },
      { value: 'mh', label: 'Marshall Islands' },
      { value: 'fm', label: 'Micronesia' },
      { value: 'nr', label: 'Nauru' },
      { value: 'nz', label: 'New Zealand' },
      { value: 'pw', label: 'Palau' },
      { value: 'pg', label: 'Papua New Guinea' },
      { value: 'ws', label: 'Samoa' },
      { value: 'sb', label: 'Solomon Islands' },
      { value: 'to', label: 'Tonga' },
      { value: 'tv', label: 'Tuvalu' },
      { value: 'vu', label: 'Vanuatu' },
    ],
  },
];