export const RoutePath = {
  Login: '/',
  Dashboard: '/dashboard',
  Workers: '/workers',
  SuperAdminRole: '/workers/super-admin-role',
  Leads: '/leads',
  Lead: '/leads/:id',
  ImportLeads: '/import-leads',
  Orders: '/orders',
  Order: '/orders/:id',
  FTDClients: '/ftd-clients',
  FTDClient: '/ftd-clients/:id',
  RetentionClients: '/retention-clients',
  RetentionClient: '/retention-clients/:id',
  LeadsAssignment: '/leads-assignment',
};
