export const RoutePath = {
  Login: '/',
  Dashboard: '/dashboard',
  Workers: '/workers',
  Worker: '/workers/:id',
  CreateWorker: '/create/worker',
  Roles: '/roles',
  Role: (id: string) => `/roles/${id}`,
  CreateRole: '/create/role',
  Leads: '/leads',
  Lead: (id: string) => `/leads/${id}`,
  ImportLeads: '/import-leads',
  Orders: '/orders',
  CreateOrder: '/create/order',
  Order: '/orders/:id',
  FTDClients: '/ftd-clients',
  FTDClient: '/ftd-clients/:id',
  RetentionClients: '/retention-clients',
  RetentionClient: '/retention-clients/:id',
  LeadsAssignment: '/leads-assignment',
  Deposits: '/deposits',
  Deposit: '/deposits/:id',
  Withdrawals: '/withdrawals',
  Withdrawal: (id: string) => `/withdrawals/${id}`,
  InternalTransfers: '/internal-transfers',
  InternalTransfer: (id: string) => `/internal-transfers/${id}`
};
